# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.26.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class Allocation:
    id: int
    orderline_id: Optional[int]
    batch_id: Optional[int]


@dataclasses.dataclass()
class Batch:
    id: int
    reference: Optional[str]
    sku: Optional[str]
    _purchased_quantity: int
    eta: Optional[datetime.date]


@dataclasses.dataclass()
class OrderLine:
    id: int
    sku: Optional[str]
    qty: int
    orderid: Optional[str]


@dataclasses.dataclass()
class Product:
    sku: str
    version_number: int
