---
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=allocation
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "54321:5432"
